# Generated by Django 4.2.6 on 2023-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reviewrating_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
