# Generated by Django 4.2.6 on 2023-10-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reviewrating_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/%Y/%m'),
        ),
    ]
